### ISSUE TITLE
.NET Observability with Open Telemetry – ECS Application service Error

### ISSUE THREAD

**Issue by vinodkumar4b9** [aws-samples/aws-dotnet-ecs-containers-observability#3]
Hi Team,

I have recently deployed the solution below regarding .NET Observability with Open Telemetry – Part 1 Metrics using Amazon Managed Prometheus and Grafana which was published in below URL 

[](https://aws.amazon.com/blogs/dotnet/net-observability-with-opentelemetry-part-1-metrics-using-amazon-prometheus-and-amazon-grafana/)
 
As part of setting up the components I have updated target group ARN in sample-app-service.json and deployed the app using the below command

**_aws ecs create-service --cluster BlogCluster --cli-input-json [file://sample-app-service.json](file:///sample-app-service.json)_**

But It seems that there is an error and  ECS service is not deploying  as expected and when I looked at logs I can see the below error

{"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for [indices:data/write/bulk] and User [name=arn:aws:iam::111********:role/Dotnet-Observability-ECSTaskRole-u1iW8b4YaX9r, backend_roles=[arn:aws:iam::111*****:role/Dotnet-Observability-ECSTaskRole-u1iW8b4YaX9r], requestedTenant=null]"}],"type":"security_exception","reason":"no permissions for [indices:data/write/bulk] and User [name=arn:aws:iam::111*******:role/Dotnet-Observability-ECSTaskRole-u1iW8b4YaX9r, backend_roles=[arn:aws:iam::11177******:role/Dotnet-Observability-ECSTaskRole-u1iW8b4YaX9r], requestedTenant=null]"},"status":403}

**Comment by kilzdavi** [comment]
Hi Vin,

This is fixed. The container image architecture was built on arm64 rather than amd64. The change was pushed to the public image. Please force a new deployment.
